matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  type: exec
  platform: ${platform}

steps:
- name: publish-linux
  image: bash
  commands:
  - ./build.sh all $CI_COMMIT_TAG
  secrets:
  - codename
  - oss_endpoint
  - oss_access_key_id
  - oss_access_key_secret
  - container_pull_secrets
  when:
    event:
    - tag
