labels:
  type: exec
  platform: linux/amd64

steps:
- name: check
  image: bash
  commands:
  - podman run --rm
      --privileged
      --network host
      -e GITHUB_TOKEN=$GITHUB_TOKEN
      -v "$(pwd):$(pwd)"
      -w "$(pwd)"
      registry.drycc.cc/drycc/python-dev
      python scripts/checker.py
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
  when:
    event:
    - cron
    - push
    - tag
