labels:
  type: exec
  platform: linux/amd64

steps:
- name: check
  image: bash
  commands:
  - podman run --rm
      --privileged
      --network host
      -e GITHUB_TOKEN=$GITHUB_TOKEN
      -v "$(pwd):$(pwd)"
      -w "$(pwd)"
      registry.drycc.cc/drycc/python-dev
      python scripts/checker.py
  secrets:
  - github_token
  - dev_registry
  - drycc_registry
  when:
    event:
    - cron
